css-two-column-layout | Richard Watanabe
Richard-Watanabe/c0621-code-solutions pull request #20
Opened 2021-06-25 22:08 UTC by Richard-Watanabe

![Screen Shot 2021-06-25 at 3 08 38 PM](https://user-images.githubusercontent.com/85139853/123489619-3c313c80-d5c7-11eb-9fc2-99865b88336c.png)

2021-06-25 22:32 UTC, codingcodymiller requested changes
Great start on this!!! A few notes for you:

2021-06-25 22:32 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  height: 1 rem;
There should not be spaces between a value and its unit

2021-06-25 22:32 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +          </p>
Your indentation here is a bit off. Remember, sibling element should always be at the same level of indentation.

2021-06-25 22:32 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +            </p>
Your indentation here is a bit off. Remember, sibling element should always be at the same level of indentation.

2021-06-25 22:32 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +            </p>
Your indentation here is a bit off. Remember, sibling element should always be at the same level of indentation.

2021-06-25 22:32 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +            </p>
Your indentation here is a bit off. Remember, sibling element should always be at the same level of indentation.

2021-06-25 22:32 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +            </p>
Your indentation here is a bit off. Remember, sibling element should always be at the same level of indentation.

2021-06-25 22:32 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +        <button>Learn more</button>
This should be indented one more tab

2021-06-25 22:50 UTC, Richard-Watanabe commented
![Screen Shot 2021-06-25 at 3 50 05 PM](https://user-images.githubusercontent.com/85139853/123491991-0727e880-d5cd-11eb-95d1-f949f424d8cc.png)

2021-06-28 21:44 UTC, codingcodymiller approved these changes
Great job on this!!!! 👏 👏 👏

2021-06-28 22:01 UTC, merged