object-manipulation-2 | Richard Watanabe
Richard-Watanabe/c0621-code-solutions pull request #66
Opened 2021-07-20 04:35 UTC by Richard-Watanabe

![Screen Shot 2021-07-19 at 9 35 17 PM](https://user-images.githubusercontent.com/85139853/126262567-e5c31112-ea19-468b-a766-14ba2ed2ede1.png)

2021-07-20 17:28 UTC, codingcodymiller requested changes

2021-07-20 17:28 UTC, codingcodymiller commented on object-manipulation-2/src/omit.js
> +    }
I believe you can do this loop to delete properties after the first loop to create the properties runs. As of right now, you are running this full loop for every property in the object as you create it, and that is a lot of extra operations for the computer.

2021-07-21 01:00 UTC, Richard-Watanabe commented
<img width="1232" alt="Screen Shot 2021-07-20 at 6 00 07 PM" src="https://user-images.githubusercontent.com/85139853/126413955-2a9cd694-631c-4b6e-8ee3-e70f2467f318.png">

2021-07-21 21:55 UTC, codingcodymiller requested changes

2021-07-21 21:55 UTC, codingcodymiller commented on object-manipulation-2/src/omit.js
> +    }
This is still inside the `for in` loop, try moving it below the `for in` loop and see if it still works 🤞

2021-07-22 04:22 UTC, Richard-Watanabe commented
![Screen Shot 2021-07-21 at 9 22 13 PM](https://user-images.githubusercontent.com/85139853/126589612-0400d1e2-493e-4ab4-803a-de5fc8c03b3c.png)

2021-08-04 22:29 UTC, codingcodymiller approved these changes

2021-08-05 04:40 UTC, merged